apiVersion: v1
kind: Service
metadata:
    name: consulta-service
spec:
    #IP externo, acessível fora do cluster
    type: NodePort
    selector:
        #todo Pod que tiver essa tag
        #fará parte desse serviço
        app: consulta
    ports:
        - name: consulta
          protocol: TCP
          #o nó recebe requisições nessa porta
          port: 6000
          #e direciona para essa porta do Pod
          targetPort: 6000